#!/bin/bash
# Builds Flubber and packages it as a macOS app (.app)
set -e
cd "$(dirname "$0")"

APP="Flubber.app"
BIN="$APP/Contents/MacOS/Flubber"

echo "🔨 Compilando Flubber..."
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# App icon (same slime pixel-art, generated by code).
./make-icon.sh
cp icon/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

swiftc -O Sources/*.swift -o "$BIN" -framework Cocoa -framework Security -framework UserNotifications

# Info.plist — LSUIElement=true => background agent (no Dock)
cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>Flubber</string>
    <key>CFBundleDisplayName</key>     <string>Flubber</string>
    <key>CFBundleIdentifier</key>      <string>co.cristiangarcia.slimepet</string>
    <key>CFBundleVersion</key>         <string>1.6.1</string>
    <key>CFBundleShortVersionString</key> <string>1.6.1</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>Flubber</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>  <string>12.0</string>
    <key>LSUIElement</key>             <true/>
    <key>NSHighResolutionCapable</key> <true/>
    <key>NSSpeechRecognitionUsageDescription</key> <string>Flubber transcribe el audio de tu reunión en el dispositivo para poder resumirla.</string>
    <key>NSMicrophoneUsageDescription</key> <string>Flubber usa el micrófono para transcribir tu voz en la reunión y poder resumirla.</string>
    <key>NSAppSleepDisabled</key>      <true/>
</dict>
</plist>
PLIST

# Signing. Priority:
#   1) FLUBBER_SIGN_ID (if you export it with a valid identity).
#   2) Local self-signed certificate "Flubber Self-Signed" (created with
#      setup-signing-cert.sh). Its fingerprint is STABLE across rebuilds, so the
#      Screen Recording permission (TCC, anchored to the cert) PERSISTS. It asks
#      for a single "Open Anyway" the first time (it is not notarized).
#   3) Ad-hoc (CI / if no cert is present). Works, but the permission resets on
#      each rebuild because the binary's fingerprint changes.
# (A REVOKED development certificate gives error 163 on open: do not use.)
SIGN_ID="$FLUBBER_SIGN_ID"
[ -z "$SIGN_ID" ] && SIGN_ID=$(security find-identity -p codesigning 2>/dev/null \
  | grep "Flubber Self-Signed" | grep -oE '[0-9A-F]{40}' | head -1)

if [ -n "$SIGN_ID" ] && security find-identity -p codesigning 2>/dev/null | grep -q "$SIGN_ID"; then
  echo "🔏 Firmando con identidad estable ($SIGN_ID) — el permiso de pantalla persiste."
  codesign --force --deep --sign "$SIGN_ID" "$APP" 2>/dev/null \
    || codesign --force --deep --sign - "$APP" 2>/dev/null || true
else
  echo "🔏 Firma ad-hoc (el permiso de pantalla se reinicia en cada rebuild)."
  codesign --force --deep --sign - "$APP" 2>/dev/null || true
fi

# Remove the "quarantine" so Gatekeeper does not block it (local app).
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true

echo "✅ Listo: $(pwd)/$APP"
echo "   Ábrelo con:  open $APP"
